package com.semanticprivacyguard.demo;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.time.Duration;

/**
 * Thin wrapper around an LLM backend that can operate in two modes:
 *
 * <ol>
 *   <li><b>Stub mode</b> (default) — generates a plausible-looking reply
 *       locally with zero network calls.  Ideal for demos and CI.</li>
 *   <li><b>Live mode</b> — forwards the sanitised prompt to a real OpenAI-
 *       compatible REST endpoint.  Enable by setting
 *       {@code llm.api-key} in {@code application.properties}.</li>
 * </ol>
 *
 * <h2>Enabling live mode</h2>
 * <pre>
 * # application.properties
 * llm.api-key=sk-...
 * llm.api-url=https://api.openai.com/v1/chat/completions
 * llm.model=gpt-4o-mini
 * </pre>
 *
 * @author Hemant Naik
 */
@Service
public class LlmStubService {

    @Value("${llm.api-key:}")
    private String apiKey;

    @Value("${llm.api-url:https://api.openai.com/v1/chat/completions}")
    private String apiUrl;

    @Value("${llm.model:gpt-4o-mini}")
    private String model;

    /**
     * Submits {@code prompt} to the configured LLM backend and returns the
     * completion text.
     *
     * @param prompt the (already-sanitised) prompt to send
     * @return the LLM's text response
     */
    public String complete(String prompt) {
        if (apiKey == null || apiKey.isBlank()) {
            return stubResponse(prompt);
        }
        try {
            return callOpenAI(prompt);
        } catch (Exception e) {
            // Fall back to stub on network error so the demo stays runnable
            return "[LLM error: " + e.getMessage() + "] — falling back to stub: "
                    + stubResponse(prompt);
        }
    }

    // ── Stub mode ─────────────────────────────────────────────────────────────

    /**
     * Generates a local response without making any network calls.
     * The stub echoes tokens back so the de-tokenization step can be
     * demonstrated end-to-end.
     */
    private static String stubResponse(String prompt) {
        // Extract the first token found (e.g. [PERSON_NAME_1])
        String firstToken = extractFirstToken(prompt);
        String greeting = firstToken.isEmpty()
                ? "Hello"
                : "Hello " + firstToken;

        return greeting + ", I've analysed your request. "
                + "Based on the information provided, your profile looks complete "
                + "and your risk level is LOW. "
                + "No further action is required at this time. "
                + "(This response was generated by the local SPG stub — set "
                + "llm.api-key in application.properties to use a real LLM.)";
    }

    private static String extractFirstToken(String text) {
        int start = text.indexOf('[');
        int end   = text.indexOf(']', start);
        if (start >= 0 && end > start) {
            return text.substring(start, end + 1);
        }
        return "";
    }

    // ── Live OpenAI mode ──────────────────────────────────────────────────────

    private String callOpenAI(String prompt) throws IOException, InterruptedException {
        String requestBody = """
                {
                  "model": "%s",
                  "messages": [
                    {"role": "system", "content": "You are a helpful assistant. \
User identifiers in square brackets like [EMAIL_1] are privacy tokens — echo them \
verbatim in your response, do not substitute them."},
                    {"role": "user",   "content": %s}
                  ],
                  "max_tokens": 512
                }
                """.formatted(model, jsonString(prompt));

        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(apiUrl))
                .timeout(Duration.ofSeconds(30))
                .header("Content-Type", "application/json")
                .header("Authorization", "Bearer " + apiKey)
                .POST(HttpRequest.BodyPublishers.ofString(requestBody))
                .build();

        HttpResponse<String> response = HttpClient.newHttpClient()
                .send(request, HttpResponse.BodyHandlers.ofString());

        if (response.statusCode() != 200) {
            throw new IOException("LLM API returned HTTP " + response.statusCode()
                    + ": " + response.body());
        }

        return extractContent(response.body());
    }

    /** Minimal JSON string escaper — avoids pulling in Jackson. */
    private static String jsonString(String s) {
        return "\"" + s.replace("\\", "\\\\")
                        .replace("\"", "\\\"")
                        .replace("\n", "\\n")
                        .replace("\r", "\\r") + "\"";
    }

    /** Extracts {@code choices[0].message.content} from an OpenAI response body. */
    private static String extractContent(String json) {
        String marker = "\"content\":";
        int idx = json.indexOf(marker);
        if (idx < 0) return json; // unexpected shape — return raw
        int start = json.indexOf('"', idx + marker.length()) + 1;
        int end   = json.indexOf('"', start);
        // Handle escaped quotes inside content
        while (end > 0 && json.charAt(end - 1) == '\\') {
            end = json.indexOf('"', end + 1);
        }
        if (start <= 0 || end <= start) return json;
        return json.substring(start, end)
                   .replace("\\n", "\n")
                   .replace("\\\"", "\"")
                   .replace("\\\\", "\\");
    }
}
